# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Release new private pod version"
  lane :release do |options|

    target_version = options[:version]

    project        = options[:project]

    path           = "#{project}.podspec"

    git_pull

    ensure_git_branch # 确认 master 分支 

    version_bump_podspec(path: path, version_number: target_version) # 更新 podspec

    git_commit_all(message: "Bump version to #{target_version}") # 提交版本号修改 

    add_git_tag(tag: target_version) # 设置 tag

    push_to_git_remote # 推送到 git 仓库 

    pod_push(path: path, repo: "55-guanping.cai-cocoapods", allow_warnings: true, sources: SOURCES) # 提交到 CocoaPods

  end

end
